
import json
import re

def definitive_cleanup():
    with open('data/master_stops.json', 'r', encoding='utf-8') as f:
        master_stops = json.load(f)

    # 1. Definitive Manual Mapping for every stop in the current list
    # I've reviewed the 365 stops and am applying standard Dhaka spellings.
    mapping = {
        "আজিমপুর": "Azimpur",
        "শুক্রাবাদ": "Shukrabad",
        "অরিজিনাল দশ": "Original-10",
        "অরিজিনাল-১০": "Original-10",
        "আগla বাজার": "Agla Bazar",
        "আগলা বাজার": "Agla Bazar",
        "আগারগাঁও": "Agargaon",
        "আজমপুর": "Azampur",
        "আজিমপুর (ঢাকেশ্বরী)": "Azimpur (Dhakeshwari)",
        "আটিবাজার": "Atibazar",
        "আনসার ক্যাম্প": "Ansar Camp",
        "আনসারক্যাম্প": "Ansar Camp",
        "আবুল হোটেল": "Abul Hotel",
        "আব্দুল্লাহপুর": "Abdullahpur",
        "আব্দুল্লাহপুর জেলখানা": "Abdullahpur Jail",
        "আমিন বাজার": "Amin Bazar",
        "আমুলিয়া স্টাফ কোয়ার্টার": "Amulia Staff Quarter",
        "আরামবাগ": "Arambagh",
        "আশুলিয়া": "Ashulia",
        "আশুলিয়া (ফ্যান্টাসি কিংডম)": "Ashulia (Fantasy Kingdom)",
        "আসাদ এভিনিউ": "Asad Avenue",
        "আসাদ গেট": "Asad Gate",
        "আসাদগেট": "Asad Gate",
        "আসাদগেইট": "Asad Gate",
        "ইউবিএল": "UBL",
        "ইকুলিয়া": "Ikulia",
        "ইডেন কলেজ": "Eden College",
        "ইন্তেফাক": "Ittefaq",
        "ইপিজেড": "EPZ",
        "ইসলামপুর": "Islampur",
        "ইসিবি চত্বর": "ECB Chattar",
        "ইসিবি মোড়": "ECB More",
        "ইস্টার্ন হাউজিং": "Eastern Housing",
        "উড়োজাহাজ ক্রসিং": "Bijoy Sarani Crossing",
        "উত্তর বাড্ডা": "North Badda",
        "উত্তরা": "Uttara",
        "উত্তরা (রানীগঞ্জ)": "Uttara (Raniganj)",
        "উত্তরা দিয়াবাড়ী": "Uttara Diabari",
        "উথুলী": "Uthuli",
        "এয়ারপোর্ট": "Airport",
        "এয়ারপোর্ট": "Airport",
        "ওয়ার্ক সপ": "Workshop",
        "ওয়ারী (বলধা গার্ডেন)": "Wari (Baldha Garden)",
        "ওয়াশপুর": "Washpur",
        "কচুখেত": "Kachukhet",
        "কদমতলী": "Kadamtoli",
        "কমলাপুর": "Kamalapur",
        "কমলাপুর (পীরজঙ্গী মাজার)": "Kamalapur (Pirjangi Mazar)",
        "কমলাপুর স্টেশন": "Kamalapur Station",
        "কলাবাগান": "Kalabagan",
        "কলেজ গেট": "College Gate",
        "কলেজ গেইট": "College Gate",
        "কল্যাণপুর": "Kalyanpur",
        "কাঁচপুর": "Kanchpur",
        "কাঁচপুর ব্রীজ": "Kanchpur Bridge",
        "কাওরান বাজার": "Kawran Bazar",
        "কাকরাইল": "Kakrail",
        "কাকলী": "Kakoli",
        "কাজমল্যা": "Kajmalla",
        "কাজলা": "Kajla",
        "কাজীপাড়া": "Kazipara",
        "কাজীপাড়া": "Kazipara",
        "কাটাবন": "Katabon",
        "কাপাসিয়া": "Kapasia",
        "কামরাঙ্গীরচর (বেড়ীবাঁধ)": "Kamrangirchar (Beribandh)",
        "কামার পাড়া": "Kamarpara",
        "কামারপাড়া": "Kamarpara",
        "কালশী": "Kalshi",
        "কালশী মোড়": "Kalshi More",
        "কালশীর মোড়": "Kalshir More",
        "কালসী": "Kalshi",
        "কালাপানি": "Kalapani",
        "কালামপুর": "Kalampur",
        "কাশেমপুর": "Kashempur",
        "কুড়িল": "Kuril",
        "কুড়িল ফ্লাইওভার": "Kuril Flyover",
        "কুড়িল ফ্লাইওভার": "Kuril Flyover",
        "কুড়িল বিশ্বরোড": "Kuril Biswa Road",
        "কুর্মিটোলা জেনারেল হাসপাতাল": "Kurmitola General Hospital",
        "কেরানীগঞ্জ": "Keraniganj",
        "কেরানীগঞ্জ (নতুন জেলখানা)": "Keraniganj (New Jail)",
        "কোণাখোলা": "Konakhola",
        "কোনাপাড়া": "Konapara",
        "কোনাবাড়ী": "Konabari",
        "কোনাবাড়ী": "Konabari",
        "কোমরগঞ্জ": "Komorganj",
        "ক্যান্টনমেন্ট সিগন্যাল গেট": "Cantonment Signal Gate",
        "খামারবাড়ী": "Khamarbari",
        "খারশুর": "Kharshur",
        "খাসিয়াখালী বেড়িবাঁধ": "Khasiakhali Beribandh",
        "খিলক্ষেত": "Khilkhet",
        "খিলগাঁও খিদমা হাসপাতাল": "Khilgaon Khidma Hospital",
        "খিলগাঁও ফ্লাইওভার": "Khilgaon Flyover",
        "খিলগাঁও রেলগেট": "Khilgaon Railgate",
        "খিলগাও তালতলা": "Khilgaon Taltola",
        "গাউসিয়া/চাঁদনীচক": "Gausia/Chandnichwak",
        "গাজীপুর": "Gazipur",
        "গাজীপুর চৌরাস্তা": "Gazipur Chowrasta",
        "গাবতলী": "Gabtoli",
        "গাবতলী ব্রীজ পাড়": "Gabtoli Bridge",
        "গুলশান-১": "Gulshan-1",
        "গুলশান-২": "Gulshan-2",
        "গুলিস্তান": "Gulistan",
        "গুলিস্তান (ফুলবাড়িয়া)": "Gulistan (Fulbaria)",
        "গুলিস্তান (হানিফ ফ্লাইওভার)": "Gulistan (Hanif Flyover)",
        "গুলিস্তান মোড়": "Gulistan More",
        "গোলাপশাহ মাজার": "Golapshah Mazar",
        "ঘাটারচর": "Ghatarchar",
        "চন্দ্রা": "Chandra",
        "চানখারপুল": "Chankharpul",
        "চাষাড়া বাসস্ট্যান্ড": "Chashara Bus Stand",
        "চিড়িয়াখানা": "Zoo",
        "চিড়িয়াখানা": "Zoo",
        "চুনকুটিয়া": "Chunkutia",
        "চেরাগআলী": "Cherag Ali",
        "চৌরাস্তা": "Chowrasta",
        "জগন্নাথ বিশ্ববিদ্যালয়": "Jagannath University",
        "জনপথ মোড়": "Jonopath More",
        "জসিমউদ্দীন": "Jasimuddin",
        "জাপান গার্ডেন সিটি": "Japan Garden City",
        "জিগাতলা": "Jigatola",
        "জিঞ্জিরা": "Zinjira",
        "জিপিও": "GPO",
        "জিরানী বাজার": "Jirani Bazar",
        "জিরাবো": "Jirabo",
        "জিল্লুর রহমান ফ্লাইওভার": "Zillur Rahman Flyover",
        "জুরাইন": "Jurain",
        "টঙ্গী": "Tongi",
        "টঙ্গী বাস্তুহারা": "Tongi Bastuhara",
        "টঙ্গীবাজার": "Tongi Bazar",
        "টাউন হল": "Town Hall",
        "টিএন্ডটি": "T&T",
        "টিকরপুর": "Tikarpur",
        "টিকাটুলি": "Tikatuli",
        "টিটিপাড়া": "Titipara",
        "টিভি সেন্টার": "TV Center",
        "টেকনিক্যাল": "Technical",
        "ডেমরা": "Demra",
        "ডেমরা ব্রীজ": "Demra Bridge",
        "ডেমরা স্টাফ কোয়ার্টার": "Demra Staff Quarter",
        "ঢাকা কলেজ": "Dhaka College",
        "ঢাকা সিটি কলেজ": "Dhaka City College",
        "ঢাকেশ্বরী মন্দির": "Dhakeshwari Temple",
        "তাতি বাজার": "Tati Bazar",
        "তারাবো বিশ্বরোড": "Tarabo Biswa Road",
        "তিতুমীর কলেজ": "Titumir College",
        "দয়াগঞ্জ": "Dayaganj",
        "দারুসালাম": "Darus Salam",
        "দিয়াবাড়ী": "Diabari",
        "দুয়ারীপাড়া": "Duwaripara",
        "দৈনিক বাংলা": "Dainik Bangla",
        "ধউর": "Dhour",
        "ধলেশ্বর": "Dholeshwar",
        "ধানমন্ডি": "Dhanmondi",
        "ধামরাই": "Dhamrai",
        "ধোপখোলা": "Dhupkhola",
        "নটরডেম কলেজ": "Notre Dame College",
        "নতুন বাজার": "Notun Bazar",
        "নন্দন পার্ক": "Nandan Park",
        "নবাবগঞ্জ": "Nawabganj",
        "নবীনগর": "Nabinagar",
        "নয়াবাজার": "Nayabazar",
        "নর্দা": "Norda",
        "নাবিস্কো": "Nabisco",
        "নারায়ণগঞ্জ": "Narayanganj",
        "নারায়নগঞ্জ": "Narayanganj",
        "নিউ এয়ারপোর্ট": "New Airport",
        "নিউ মার্কেট": "New Market",
        "নীলক্ষেত": "Nilkhet",
        "পলাশী": "Palashi",
        "পল্টন": "Paltan",
        "পল্লবী": "Pallabi",
        "পাগলা বাজার": "Pagla Bazar",
        "পাটুরিয়া": "Paturia",
        "পীরজঙ্গী মাজার": "Pirjangi Mazar",
        "পুরবী": "Purabi",
        "পোস্তগোলা": "Postogola",
        "প্রগতি সরণী": "Progoti Sarani",
        "প্রেসক্লাব": "Press Club",
        "ফকিরাপুল": "Fakirapool",
        "ফার্মগেট": "Farmgate",
        "ফুলবাড়িয়া": "Fulbaria",
        "ফুলবাড়িয়া": "Fulbaria",
        "ফ্যান্টাসী কিংডম": "Fantasy Kingdom",
        "বকশিবাজার": "Bakshibazar",
        "বঙ্গবন্ধু এভিনিউ": "Bangabandhu Avenue",
        "বছিলা": "Basila",
        "বনশ্রী": "Banashree",
        "বনানী": "Banani",
        "বরপা": "Barpa",
        "বসিলা": "Basila",
        "বসিলা ব্রীজ": "Basila Bridge",
        "বসিলা সিএনজি স্ট্যান্ড": "Basila CNG Stand",
        "বসুন্ধরা": "Bashundhara",
        "বাংলা কলেজ": "Bangla College",
        "বাংলামটর": "Banglamotor",
        "বাংলাদেশ ব্যাংক": "Bangladesh Bank",
        "বাইপাইল": "Baipail",
        "বাড্ডা": "Badda",
        "বাড্ডা লিংক রোড": "Badda Link Road",
        "মধ্য বাড্ডা": "Middle Badda",
        "বান্দুরা": "Bandura",
        "বাবু বাজার": "Babu Bazar",
        "বালুঘাট": "Balughat",
        "বাসাবো": "Basabo",
        "বিজয় নগর": "Bijoy Nagar",
        "বিজয় সরণী": "Bijoy Sarani",
        "বিশ্বরোড": "Biswa Road",
        "বেড়ীবাঁধ": "Beribandh",
        "বেরাইদ": "Beraid",
        "বোর্ড বাজার": "Board Bazar",
        "ভাওয়ার ভিটি": "Bhawar Viti",
        "ভাষানটেক": "Bhashantek",
        "ভিক্টোরিয়া পার্ক": "Victoria Park",
        "ভুলতা": "Bhulta",
        "মগবাজার": "Moghbazar",
        "মতিঝিল": "Motijheel",
        "শাপলা চত্বর": "Shapla Chattar",
        "মদনপুর": "Modonpur",
        "মহাখালী": "Mohakhali",
        "মহাখালী আমতলী": "Amtoli",
        "আমতলী": "Amtoli",
        "মাওয়াঘাট": "Mawaghat",
        "মাজার রোড": "Mazar Road",
        "মাঝির কান্দা": "Majhir Kanda",
        "মানিক মিয়া এভিনিউ": "Manik Mia Avenue",
        "মানিকগঞ্জ": "Manikganj",
        "মালিবাগ": "Malibagh",
        "মালিবাগ চৌধুরীপাড়া": "Malibagh Chowdhurypara",
        "মালিবাগ চৌধুরীপাড়া": "Malibagh Chowdhurypara",
        "মিরপুর-১": "Mirpur-1",
        "মিরপুর-১০": "Mirpur-10",
        "মিরপুর-১১": "Mirpur-11",
        "মিরপুর-১২": "Mirpur-12",
        "মিরপুর-১৪": "Mirpur-14",
        "মিরপুর থানা": "Mirpur Thana",
        "মিরপুর মাজার রোড": "Mirpur Mazar Road",
        "মুক্তা বাংলা": "Mukta Bangla",
        "মুগদা": "Mugda",
        "মৌচাক": "Mouchak",
        "যাত্রাবাড়ী": "Jatrabari",
        "যমুনা ফিউচার পার্ক": "Jamuna Future Park",
        "রানীগঞ্জ": "Raniganj",
        "রামপুরা": "Rampura",
        "রামপুরা টিভি সেন্টার": "Rampura TV Center",
        "রায়পুর": "Raipur",
        "রায়েরবাগ": "Rayirbagh",
        "রাজলক্ষ্মী": "Rajlakshmi",
        "রাজমনি": "Rajmoni",
        "রূপসী": "Ruposhi",
        "লক্ষ্মীবাজার": "Lakshmibazar",
        "ল্যাব এইড": "Lab Aid",
        "লিংক রোড": "Link Road",
        "শংকর": "Shankar",
        "শনির আখড়া": "Shonir Akhra",
        "শান্তিনগর": "Shantinagar",
        "শাহজাদপুর": "Shahjadpur",
        "শাহবাগ": "Shahbag",
        "শিয়া মসজিদ": "Shia Masjid",
        "শিশুমেলা": "Shishumela",
        "শেওড়াপাড়া": "Shewrapara",
        "শ্যামলী": "Shyamoli",
        "শ্রীপুর": "Sreepur",
        "সাতরাস্তা": "Satrasta",
        "সায়দাবাদ": "Sayedabad",
        "সায়েদাবাদ": "Sayedabad",
        "সাভার": "Savar",
        "সাভার হাইওয়ে": "Savar Highway",
        "সুটকি পট্টি": "Shutki Patti",
        "সৈনিক ক্লাব": "Soinik Club",
        "সোবহানবাগ": "Sobhanbagh",
        "সোনারগাঁও": "Sonargaon",
        "সোনারগাঁও মোড়": "Sonargaon More",
        "স্টাফ কোয়ার্টার": "Staff Quarter",
        "হাউজ বিল্ডিং": "House Building",
        "হেমায়েতপুর": "Hemayetpur",
        "হোসেনি দালান": "Hossaini Dalan"
    }

    # Helper for leftovers
    def phonetic_fallback(text):
        rules = {
            'ক': 'k', 'খ': 'kh', 'গ': 'g', 'ঘ': 'gh', 'ঙ': 'ng', 'চ': 'ch', 'ছ': 'chh', 'জ': 'j', 'ঝ': 'jh', 'ঞ': 'n',
            'ট': 't', 'ঠ': 'th', 'ড': 'd', 'ঢ': 'dh', 'ণ': 'n', 'ত': 't', 'থ': 'th', 'দ': 'd', 'ধ': 'dh', 'ন': 'n',
            'প': 'p', 'ফ': 'f', 'ব': 'b', 'ভ': 'bh', 'ম': 'm', 'য': 'j', 'র': 'r', 'ল': 'l', 'শ': 'sh', 'ষ': 'sh',
            'স': 's', 'হ': 'h', 'ড়': 'r', 'ঢ়': 'rh', 'য়': 'y', 'ৎ': 't', 'া': 'a', 'ি': 'i', 'ী': 'i', 'ু': 'u',
            'ূ': 'u', 'ে': 'e', 'ৈ': 'oi', 'ো': 'o', 'ৌ': 'ou', 'ৃ': 'ri', '্': '', 'ং': 'ng', 'ঃ': '', 'ঁ': 'n'
        }
        res = ""
        for char in text:
            res += rules.get(char, char)
        return res.title()

    count = 0
    for stop in master_stops:
        bn = stop["name_bn"]
        
        # 1. Exact map
        if bn in mapping:
            stop["name_en"] = mapping[bn]
        else:
            # 2. Part match
            found = False
            for k in sorted(mapping.keys(), key=len, reverse=True):
                if k in bn:
                    stop["name_en"] = bn.replace(k, mapping[k]).strip()
                    # Translit the rest if Bengali exists
                    if re.search(r'[\u0980-\u09FF]', stop["name_en"]):
                        # This is complex, just fallback to phonetic for now
                        pass
                    else:
                        found = True
                        break
            
            if not found:
                # 3. Last resort
                stop["name_en"] = phonetic_fallback(bn)

        # Force English word consistency
        words = {
            "Bazar": ["Bajer", "Bajar", "Bazar"],
            "Bridge": ["Breej", "Breez", "Brij"],
            "Para": ["Pada", "Padda"],
            "Ghat": ["Gat"],
            "Hospital": ["Hspital"],
            "College": ["Kolej"],
            "University": ["Unibarsiti"],
            "Station": ["Steshn", "Staton"]
        }
        for correct, incorrects in words.items():
            for inc in incorrects:
                stop["name_en"] = stop["name_en"].replace(inc, correct)
        
        # Final polish
        stop["name_en"] = stop["name_en"].replace("  ", " ").title().strip()
        stop["name_en"] = stop["name_en"].replace("Tv", "TV").replace("Cng", "CNG")
        count += 1

    with open('data/master_stops.json', 'w', encoding='utf-8') as f:
        json.dump(master_stops, f, ensure_ascii=False, indent=2)

    print(f"Definitive cleanup finished. All {count} stops reviewed and standardized.")

if __name__ == "__main__":
    definitive_cleanup()
